name: deferential_expression
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - r-base>=4.0
  - rpy2
  - bioconductor-edger
  - bioconductor-limma
  - pip
  - pip:
      - scanpy
      - anndata
      - numpy
      - pandas
      - matplotlib
      - seaborn
      - jupyterlab
      - singlecellexperiment
      - summarizedexperiment
      - biocutils
      - plotnine
      - scikit-learn
      - statsmodels
      - "bioc2ri @ git+https://github.com/MaximilianNuber/bioc2ri.git@master"
      - "deferential_expression @ git+https://github.com/MaximilianNuber/deferential_expression.git@main"